package com.refsul.inventory_refsul.View;

public class Home extends javax.swing.JFrame {
    public Home() {
        initComponents();
        this.setExtendedState( MAXIMIZED_BOTH );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneHome = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        navBar = new javax.swing.JMenuBar();
        optionMenu = new javax.swing.JMenu();
        ItemHelp = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ItemClose = new javax.swing.JMenuItem();
        optionSales = new javax.swing.JMenu();
        ItemMakeSale = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ItemSalesDetails = new javax.swing.JMenuItem();
        optionStaff = new javax.swing.JMenu();
        ItemSellers = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        ItemProviders = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        ItemCustomers = new javax.swing.JMenuItem();
        optionInventory = new javax.swing.JMenu();
        ItemProducts = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        ItemPaymentMethods = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        ItemUnitsMeasurements = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        ItemBrands = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPaneHome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ac.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(828, 302));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/184.png"))); // NOI18N

        jDesktopPaneHome.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneHome.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneHomeLayout = new javax.swing.GroupLayout(jDesktopPaneHome);
        jDesktopPaneHome.setLayout(jDesktopPaneHomeLayout);
        jDesktopPaneHomeLayout.setHorizontalGroup(
            jDesktopPaneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneHomeLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(136, 136, 136)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jDesktopPaneHomeLayout.setVerticalGroup(
            jDesktopPaneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneHomeLayout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(jDesktopPaneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneHomeLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );

        navBar.setBackground(new java.awt.Color(255, 255, 255));
        navBar.setPreferredSize(new java.awt.Dimension(74, 70));

        optionMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        optionMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        optionMenu.setLabel("  Menu");
        optionMenu.setMargin(new java.awt.Insets(0, 10, 0, 0));
        optionMenu.setMaximumSize(new java.awt.Dimension(130, 32767));

        ItemHelp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ItemHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer-service.png"))); // NOI18N
        ItemHelp.setText("  Help");
        ItemHelp.setMargin(new java.awt.Insets(10, 15, 10, 10));
        ItemHelp.setPreferredSize(new java.awt.Dimension(200, 50));
        optionMenu.add(ItemHelp);
        optionMenu.add(jSeparator1);

        ItemClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ItemClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit-door.png"))); // NOI18N
        ItemClose.setText("  Close");
        ItemClose.setMargin(new java.awt.Insets(10, 15, 10, 10));
        ItemClose.setPreferredSize(new java.awt.Dimension(200, 50));
        optionMenu.add(ItemClose);

        navBar.add(optionMenu);

        optionSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trolley.png"))); // NOI18N
        optionSales.setText("  Sales");
        optionSales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        optionSales.setMargin(new java.awt.Insets(0, 20, 0, 0));
        optionSales.setMaximumSize(new java.awt.Dimension(130, 32767));

        ItemMakeSale.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ItemMakeSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/point-of-sale.png"))); // NOI18N
        ItemMakeSale.setText("  Help");
        ItemMakeSale.setMargin(new java.awt.Insets(10, 15, 10, 10));
        ItemMakeSale.setPreferredSize(new java.awt.Dimension(200, 50));
        optionSales.add(ItemMakeSale);
        optionSales.add(jSeparator2);

        ItemSalesDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ItemSalesDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sales.png"))); // NOI18N
        ItemSalesDetails.setText("  Sales Details");
        ItemSalesDetails.setMargin(new java.awt.Insets(10, 15, 10, 10));
        ItemSalesDetails.setPreferredSize(new java.awt.Dimension(200, 50));
        optionSales.add(ItemSalesDetails);

        navBar.add(optionSales);

        optionStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office-staff.png"))); // NOI18N
        optionStaff.setText("  Staff");
        optionStaff.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        optionStaff.setMargin(new java.awt.Insets(0, 20, 0, 0));
        optionStaff.setMaximumSize(new java.awt.Dimension(130, 32767));

        ItemSellers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ItemSellers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/avatar.png"))); // NOI18N
        ItemSellers.setText("  Sellers");
        ItemSellers.setMargin(new java.awt.Insets(10, 15, 10, 10));
        ItemSellers.setPreferredSize(new java.awt.Dimension(200, 50));
        optionStaff.add(ItemSellers);
        optionStaff.add(jSeparator4);

        ItemProviders.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ItemProviders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/providers.png"))); // NOI18N
        ItemProviders.setText("  Providers");
        ItemProviders.setToolTipText("");
        ItemProviders.setMargin(new java.awt.Insets(10, 15, 10, 10));
        ItemProviders.setPreferredSize(new java.awt.Dimension(200, 50));
        optionStaff.add(ItemProviders);
        optionStaff.add(jSeparator3);

        ItemCustomers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ItemCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/client.png"))); // NOI18N
        ItemCustomers.setText("  Customers");
        ItemCustomers.setToolTipText("");
        ItemCustomers.setMargin(new java.awt.Insets(10, 15, 10, 10));
        ItemCustomers.setPreferredSize(new java.awt.Dimension(200, 50));
        optionStaff.add(ItemCustomers);

        navBar.add(optionStaff);

        optionInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inventory.png"))); // NOI18N
        optionInventory.setText("  Inventory");
        optionInventory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        optionInventory.setMargin(new java.awt.Insets(0, 20, 0, 0));
        optionInventory.setMaximumSize(new java.awt.Dimension(180, 32767));

        ItemProducts.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ItemProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/products.png"))); // NOI18N
        ItemProducts.setText("  Products");
        ItemProducts.setMargin(new java.awt.Insets(10, 15, 10, 10));
        ItemProducts.setPreferredSize(new java.awt.Dimension(200, 50));
        optionInventory.add(ItemProducts);
        optionInventory.add(jSeparator5);

        ItemPaymentMethods.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ItemPaymentMethods.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/payment Methods.png"))); // NOI18N
        ItemPaymentMethods.setText("  PaymentMethods");
        ItemPaymentMethods.setMargin(new java.awt.Insets(10, 15, 10, 10));
        ItemPaymentMethods.setPreferredSize(new java.awt.Dimension(260, 50));
        optionInventory.add(ItemPaymentMethods);
        optionInventory.add(jSeparator6);

        ItemUnitsMeasurements.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ItemUnitsMeasurements.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unit-m.png"))); // NOI18N
        ItemUnitsMeasurements.setText("  Units Measurements");
        ItemUnitsMeasurements.setMargin(new java.awt.Insets(10, 15, 10, 10));
        ItemUnitsMeasurements.setPreferredSize(new java.awt.Dimension(200, 50));
        optionInventory.add(ItemUnitsMeasurements);
        optionInventory.add(jSeparator7);

        ItemBrands.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ItemBrands.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brands.png"))); // NOI18N
        ItemBrands.setText("  Brands");
        ItemBrands.setMargin(new java.awt.Insets(10, 15, 10, 10));
        ItemBrands.setPreferredSize(new java.awt.Dimension(200, 50));
        optionInventory.add(ItemBrands);

        navBar.add(optionInventory);

        setJMenuBar(navBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneHome, javax.swing.GroupLayout.DEFAULT_SIZE, 1742, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneHome, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemBrands;
    private javax.swing.JMenuItem ItemClose;
    private javax.swing.JMenuItem ItemCustomers;
    private javax.swing.JMenuItem ItemHelp;
    private javax.swing.JMenuItem ItemMakeSale;
    private javax.swing.JMenuItem ItemPaymentMethods;
    private javax.swing.JMenuItem ItemProducts;
    private javax.swing.JMenuItem ItemProviders;
    private javax.swing.JMenuItem ItemSalesDetails;
    private javax.swing.JMenuItem ItemSellers;
    private javax.swing.JMenuItem ItemUnitsMeasurements;
    private javax.swing.JDesktopPane jDesktopPaneHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JMenuBar navBar;
    private javax.swing.JMenu optionInventory;
    private javax.swing.JMenu optionMenu;
    private javax.swing.JMenu optionSales;
    private javax.swing.JMenu optionStaff;
    // End of variables declaration//GEN-END:variables
}
