package com.refsul.inventory_refsul.view.internalsFrame;

import com.refsul.inventory_refsul.controllers.BrandController;
import com.refsul.inventory_refsul.models.Brand;
import com.refsul.inventory_refsul.view.validators.ItemForm;
import com.refsul.inventory_refsul.view.validators.validationOptions.LengthValidator;
import com.refsul.inventory_refsul.view.validators.validationOptions.RequiredValidator;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.List;

public class UIBrand extends javax.swing.JInternalFrame {
    BrandController brandController;
    DefaultTableModel tableModel;
    Brand brand;
    private int idBrand;

    public UIBrand() throws SQLException {
        initComponents();
        this.setResizable( false );

        this.brandController = new BrandController();
        this.tableModel = new DefaultTableModel();
        this.brand = new Brand();
        this.idBrand = 0;
        
        this.cleanListBrands();
        this.showListBrands();

        this.disableButtonUpdateAndDelete();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel01 = new javax.swing.JPanel();
        jLabel01 = new javax.swing.JLabel();
        jLabel02 = new javax.swing.JLabel();
        jLabel03 = new javax.swing.JLabel();
        jLabel04 = new javax.swing.JLabel();
        jPanel02 = new javax.swing.JPanel();
        jLabel05 = new javax.swing.JLabel();
        jLabel06 = new javax.swing.JLabel();
        jTextDescription = new javax.swing.JTextField();
        jLabel07 = new javax.swing.JLabel();
        jLabel08 = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonCleanInput = new javax.swing.JButton();
        jPanel03 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBrand = new javax.swing.JTable();
        jLabel09 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jPanel01.setBackground(new java.awt.Color(255, 255, 255));
        jPanel01.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGO44.gif"))); // NOI18N

        jLabel02.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel02.setText("Refaccioraria REFSUL");

        jLabel03.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel03.setText("En este apartado usted podrá Agregar nuevas Marcas.");

        jLabel04.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel04.setText("También Editar su información y Eliminar ");

        javax.swing.GroupLayout jPanel01Layout = new javax.swing.GroupLayout(jPanel01);
        jPanel01.setLayout(jPanel01Layout);
        jPanel01Layout.setHorizontalGroup(
            jPanel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel01Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel01)
                .addGroup(jPanel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel01Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel02))
                    .addGroup(jPanel01Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel03))
                    .addGroup(jPanel01Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel04)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel01Layout.setVerticalGroup(
            jPanel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel01Layout.createSequentialGroup()
                        .addComponent(jLabel02)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel03)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel04))
                    .addComponent(jLabel01))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel02.setBackground(new java.awt.Color(255, 255, 255));
        jPanel02.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel05.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel05.setText("Llene todos los campos Para realizar cualquier acción");

        jLabel06.setText("Descripción de la Marca:");

        jTextDescription.setVerifyInputWhenFocusTarget(false);

        jLabel07.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel07.setText("Acciónes");

        jLabel08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Brands_Banner.png"))); // NOI18N

        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        buttonAdd.setText("Agregar");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    buttonAddActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        buttonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar.png"))); // NOI18N
        buttonUpdate.setText("Editar");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    buttonUpdateActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        buttonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        buttonDelete.setText("Eliminar");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    buttonDeleteActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        buttonCleanInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clean.png"))); // NOI18N
        buttonCleanInput.setText("Limpiar");
        buttonCleanInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCleanInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel02Layout = new javax.swing.GroupLayout(jPanel02);
        jPanel02.setLayout(jPanel02Layout);
        jPanel02Layout.setHorizontalGroup(
            jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel02Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel02Layout.createSequentialGroup()
                        .addComponent(jLabel07)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel02Layout.createSequentialGroup()
                        .addComponent(buttonAdd)
                        .addGap(18, 18, 18)
                        .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonDelete)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCleanInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel02Layout.createSequentialGroup()
                        .addComponent(jLabel05)
                        .addGap(30, 30, 30)))
                .addComponent(jLabel08)
                .addGap(29, 29, 29))
            .addGroup(jPanel02Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel06)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel02Layout.setVerticalGroup(
            jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel05)
                .addGap(27, 27, 27)
                .addGroup(jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel06, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel07)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCleanInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jLabel08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel03.setBackground(new java.awt.Color(255, 255, 255));
        jPanel03.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableBrand.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBrandMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBrand);

        jLabel09.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel09.setText("En este apartado podrás Visualizar la lista de Marcas Registrados");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel10.setText("Seleccione una Columna a Editar o Eliminar");

        javax.swing.GroupLayout jPanel03Layout = new javax.swing.GroupLayout(jPanel03);
        jPanel03.setLayout(jPanel03Layout);
        jPanel03Layout.setHorizontalGroup(
            jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel03Layout.createSequentialGroup()
                .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel03Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel03Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel09))
                    .addGroup(jPanel03Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel03Layout.setVerticalGroup(
            jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel03Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel09, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel03, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel02, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean isValidInput()
    {
        ItemForm description = new ItemForm( "Descripción", this.jTextDescription.getText() )
                .addValidador( new RequiredValidator() )
                .addValidador( new LengthValidator( 3, 20 ));

        if( !description.isValid() ) {
            description.printMessage();
            this.jTextDescription.requestFocus();
            return false;
        }

        return true;
    }

    private void buttonAddActionPerformed( java.awt.event.ActionEvent evt ) throws SQLException
    {
        this.idBrand = 0;
        this.buildBrand();

        if( this.isValidInput() ) {
            if( this.brandController.createBrand( this.brand ) ) {
                this.completeAddAction();
                JOptionPane.showMessageDialog( null, "Método de pago agregado correctamente",
                        "Método de pago agregado", JOptionPane.INFORMATION_MESSAGE );
            } else {
                JOptionPane.showMessageDialog( null, "Error al agregar nuevo Método de pago",
                        "Error al agregar", JOptionPane.WARNING_MESSAGE );
            }
        }
    }

    public void showListBrands() throws SQLException
    {
        List<Brand> listBrands = this.brandController.getBrands();
        this.tableModel = ( DefaultTableModel ) this.tableBrand.getModel();

        for( Brand brand : listBrands )
        {
            this.tableModel.addRow( new Object[]{ brand.getIdBrand(), brand.getDescription() } );
        }
    }

    private void tableBrandMouseClicked( java.awt.event.MouseEvent evt )
    {
        this.disableButtonAdd();
        this.activeButtonUpdateAndDelete();

        int selectedItem = this.tableBrand.rowAtPoint( evt.getPoint() );
        this.idBrand = Integer.parseInt( this.tableBrand.getValueAt( selectedItem, 0 ) + "" );
        this.jTextDescription.setText( this.tableBrand.getValueAt( selectedItem, 1 ) + "" );
    }

    private void buttonUpdateActionPerformed( java.awt.event.ActionEvent evt ) throws SQLException
    {
        this.buildBrand();

        if( this.isValidInput() ) {
            int confirm = JOptionPane.showConfirmDialog( null, "¿Desea guardar cambios?\n" +
                            "Los datos del Método de pago se modificaran" , "Actualizando Método de pago",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE );

            if( confirm == 0 )
            {
                if( this.brandController.updateBrand( this.brand ) ) {
                    this.completeDeleteOrUpdateAction();
                    JOptionPane.showMessageDialog( null, "Método de pago actualizado correctamente",
                            "Método de pago actualizado", JOptionPane.INFORMATION_MESSAGE );
                } else {
                    JOptionPane.showMessageDialog( null, "Error al actualizar Método de pago",
                            "Error al actualizar", JOptionPane.WARNING_MESSAGE );
                }
            }
        }
    }

    private void buttonDeleteActionPerformed( java.awt.event.ActionEvent evt ) throws SQLException
    {
        int confirm = JOptionPane.showConfirmDialog( null, "¿Desea eliminar el Método de pago?\n" +
                        "El Método de pago se eliminará permanentemente" , "Eliminar Método de pago",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE );

        if( confirm == 0 ) {
            this.brandController.deleteBrand( this.idBrand );
            this.completeDeleteOrUpdateAction();
            JOptionPane.showMessageDialog( null, "Método de pago se elimino correctamente",
                    "Método de pago eliminado", JOptionPane.INFORMATION_MESSAGE );
        }
    }

    private void buttonCleanInputActionPerformed( java.awt.event.ActionEvent evt )
    {
        this.cleanFormInput();
        this.disableButtonUpdateAndDelete();
        this.activeButtonAdd();
    }
    
    public void cleanListBrands()
    {
        this.tableModel = ( DefaultTableModel ) this.tableBrand.getModel();
        for( int i = this.tableModel.getRowCount() - 1 ; i >= 0 ; i-- )
        {
            this.tableModel.removeRow( i );
        }
    }

    private void cleanFormInput()
    {
        this.jTextDescription.setText( null );
    }

    private void disableButtonAdd()
    {
        this.buttonAdd.setEnabled( false );
    }

    private void disableButtonUpdateAndDelete()
    {
        this.buttonUpdate.setEnabled( false );
        this.buttonDelete.setEnabled( false );
    }

    private void activeButtonAdd()
    {
        this.buttonAdd.setEnabled( true );
    }

    private void activeButtonUpdateAndDelete()
    {
        this.buttonUpdate.setEnabled( true );
        this.buttonDelete.setEnabled( true );
    }

    private void completeAddAction() throws SQLException
    {
        this.cleanListBrands();
        this.showListBrands();
        this.cleanFormInput();
    }
    private void completeDeleteOrUpdateAction() throws SQLException
    {
        this.cleanListBrands();
        this.cleanFormInput();
        this.showListBrands();
        this.disableButtonUpdateAndDelete();
        this.activeButtonAdd();
    }

    private void buildBrand() {
        this.brand.setIdBrand( this.idBrand );
        this.brand.setDescription( jTextDescription.getText() );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonCleanInput;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonUpdate;
    javax.swing.JLabel jLabel01;
    javax.swing.JLabel jLabel02;
    javax.swing.JLabel jLabel03;
    javax.swing.JLabel jLabel04;
    javax.swing.JLabel jLabel05;
    javax.swing.JLabel jLabel06;
    javax.swing.JLabel jLabel07;
    javax.swing.JLabel jLabel08;
    javax.swing.JLabel jLabel09;
    javax.swing.JLabel jLabel10;
    javax.swing.JPanel jPanel01;
    javax.swing.JPanel jPanel02;
    javax.swing.JPanel jPanel03;
    javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextDescription;
    private javax.swing.JTable tableBrand;
    // End of variables declaration//GEN-END:variables
}
